### ISSUE TITLE
Support Google auth as user to enable DSS data loading from EC2 instance

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-dss-data-loader#1]
Identify how to do programmatic Google auth as/for user account, so DSS data loading can be run on an EC2 instance

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/LOAD-11)
┆Project Name: CGP-Data Loader
┆Issue Number: LOAD-11
┆Epic: Loader Improvements

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This can probably be addressed working out and documenting the steps for the appropriate use of the “gcloud auth” command and associated credential files.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This will also be facilitated by current work on TLP‌-720.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This issue will be resolved by the work Lon is doing for TLP‌-720.

**Comment by DailyDreaming** [comment]
Closed by #49.
