### ISSUE TITLE
Update data loader to use updated HCA initialization code

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-dss-data-loader#35]
This was noted by Hannes [here](https://github.com/HumanCellAtlas/dcp-cli/issues/142).

Here is some of his commentary

{quote}The prescribed method to switch the DSSClient to a different host is

```python
client = hca.dss.DSSClient()
client.host = "https://dss.example.com/v1"
```

There are two problems with this approach:

For one the swagger def is downloaded (or loaded from disk) in the constructor, defaulting to the HCA prod instance. There is no guarantee that the `dss.example.com` endpoint has a compatible API.

More puzzling is that the client seems to sporadically revert to using the prod instance, even when configured to a different host as outlined above. This must be a race condition. I do have multiple threads sharing a client.

If I instantiate the client in the following way, the problem goes away (the client does not revert to prod):

```python
config = HCAConfig("hca")
 config['DSSClient'].swagger_url = 'https://dss.example.com/v1/swagger.json'
 self.dss_client = DSSClient(config=config)
```

This is all I got, I don't have time to dig deeper right now.{quote}

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/LOAD-40)
┆Project Name: CGP-Data Loader
┆Issue Number: LOAD-40
┆Epic: Loader Improvements

**Comment by calvinnhieu** [comment]
Hey guys, I'm looking into this issue now and to keep things organized I'll be posting updates on this [Hannes' issue](https://app.zenhub.com/workspace/o/humancellatlas/dcp-cli/issues/142) in HCA

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

The HCA CLI / python bindings has updated their recommended code sequence for initializing the python bindings. We need need to update our base loader (and tests, if applicable) to use this new sequence, which is documented here:
[https://hca.readthedocs.io/en/latest/](https://hca.readthedocs.io/en/latest/)

This applies equally to both single-threaded and multi-threaded use of HCA python bindings.
