### ISSUE TITLE
Tests failing with 401 for Google credentials

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/cgp-dss-data-loader#38]
Google credentials need to be updated for Travis. Hopefully this will fix failing tests.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/LOAD-43)
┆Project Name: CGP-Data Loader
┆Issue Number: LOAD-43

**Comment by jessebrennan** [comment]
Increasing permissions for travis credentials fixed this, but a better solution is to set up special test buckets with varying levels of permissions to make sure access rejection / acceptance works as expected.

**Comment by cricketsloan** [comment]
➤ Jesse Brennan commented:

This works as configured, and upon review, no changes seem necessary at this point.
