### ISSUE TITLE
Add support for specifying UUID (and version?) for files and bundles

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-dss-data-loader#8]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/LOAD-4)
┆Project Name: CGP-Data Loader
┆Issue Number: LOAD-4
┆Epic: Develop CGP DSS Core Data Loader

**Comment by cricketsloan** [comment]
➤ Jesse Brennan commented:

Just need to use version info from gen3 data instead of timestamp when uploading data file

**Comment by jessebrennan** [comment]
Version support is integrated. PR coming soon.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

The loader needs to provide file and bundle UUIDs and versions for the data store to use.
